image: zenika/alpine-chrome:latest

stages:
  - test
  - build
  - deploy

cache:
  key: build-cache
  paths:
    - node_modules/
    - dist/

build:
  stage: build
  script:
    - yarn install
    - npm run webpack
  artifacts:
    untracked: true
  only:
    - master

test:
  stage: test
  script:
    - yarn install
    - yarn run tslint
    - yarn run test
  artifacts:
    untracked: true

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r dist/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master