image: node:latest

stages:
  - lint
  - build
  - deploy

cache:
  key: build-cache
  paths:
    - node_modules/
    - dist/

test_tslint:
  stage: lint
  script:
    - yarn install
    - yarn run tslint
  cache:
    key: build-cache
    paths:
      - node_modules/
      - dist/

build:
  stage: build
  script:
    - yarn install
    - yarn run webpack
  cache:
    key: build-cache

pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r dist/* .public
  - mv .public public
  cache:
    key: build-cache
  artifacts:
    paths:
    - public
  only:
  - master