image: node:latest

stages:
  - lint
  - build
  - deploy

cache:
  paths:
    - node_modules/

test_tslint:
  stage: lint
  script:
    - yarn install
    - yarn run tslint

build:
  stage: build
  script:
    - yarn install
    - yarn run webpack

pages:
  stage: deploy
  script:
  - yarn install
  - yarn run webpack
  - mkdir .public
  - cp -r dist/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master