/** Declaration file generated by dts-gen */

declare module 'didi' {

    export function Injector(modules: any, parent: any, ...args: any[]): any;
    
    export function Module(): any;
    
    export function annotate(...args: any[]): any;
    
    export namespace Injector {
        const prototype: {
        };
    
    }
    
    export namespace Module {
        const prototype: {
        };
    
    }
    
    export namespace annotate {
        const prototype: {
        };
    
    }

}    
