/** Declaration file generated by dts-gen */

// export = path_intersection;
declare module "path-intersection" {

    export default function path_intersection(path1: any, path2: any, justCount?: any): any;
    
    // declare namespace path_intersection {
    //     const prototype: {
    //     };
    
    // }
}

